//Session
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//User
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";
export const UPDATE_PROFILE_IMAGE_SUCCESS = "UPDATE_PROFILE_IMAGE_SUCCESS";
export const UPDATE_PROFILE_IMAGE_FAILURE = "UPDATE_PROFILE_IMAGE_FAILURE";
export const REMOVE_PROFILE_IMAGE_SUCCESS = "REMOVE_PROFILE_IMAGE_SUCCESS";
export const REMOVE_PROFILE_IMAGE_FAILURE = "REMOVE_PROFILE_IMAGE_FAILURE";

//UI
export const ASYNC_REQUEST = "ASYNC_REQUEST";
export const BROWSER_ROUTE_CHANGED = 'BROWSER_ROUTE_CHANGED';
export const SHOW_PROFILE_PHOTO_MODAL = "SHOW_PROFILE_PHOTO_MODAL";
export const HIDE_PROFILE_PHOTO_MODAL = "HIDE_PROFILE_PHOTO_MODAL";

//Image
export const IMAGE_SELECT_SUCCESS = "IMAGE_SELECT_SUCCESS";
export const IMAGE_SELECT_FAILURE = "IMAGE_SELECT_FAILURE";
export const IMAGE_SAVED_SUCCESS = "IMAGE_SAVED_SUCCESS";
export const UPDATE_IMAGE_FILTERS = "UPDATE_IMAGE_FILTERS";