//Session
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//User
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const UPDATE_USER_AVATAR_REQUEST =  "UPDATE_USER_AVATAR_REQUEST"
export const UPDATE_USER_AVATAR_SUCCESS = "UPDATE_USER_AVATAR_SUCCESS";
export const UPDATE_USER_AVATAR_FAILURE = "UPDATE_USER_AVATAR_FAILURE";

export const REMOVE_USER_AVATAR_REQUEST = "REMOVE_USER_AVATAR_REQUEST"
export const REMOVE_USER_AVATAR_SUCCESS = "REMOVE_USER_AVATAR_SUCCESS";
export const REMOVE_USER_AVATAR_FAILURE = "REMOVE_USER_AVATAR_FAILURE";

//Explore
export const FOUND_USERS_REQUEST = "FOUND_USERS_REQUEST";
export const FOUND_USERS_SUCCESS = "FOUND_USERS_SUCCESS";
export const FOUND_USERS_FAILURE = "FOUND_USERS_FAILURE";

//Users
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

//UI
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SHOW_USER_PHOTO_MODAL = "SHOW_USER_PHOTO_MODAL";
export const HIDE_USER_PHOTO_MODAL = "HIDE_USER_PHOTO_MODAL";
export const SHOW_LOGOUT_MODAL = "SHOW_LOGOUT_MODAL";
export const HIDE_LOGOUT_MODAL = "HIDE_LOGOUT_MODAL";

//Image
export const IMAGE_SELECT_SUCCESS = "IMAGE_SELECT_SUCCESS";
export const IMAGE_SELECT_FAILURE = "IMAGE_SELECT_FAILURE";
export const IMAGE_SAVED_SUCCESS = "IMAGE_SAVED_SUCCESS";
export const UPDATE_IMAGE_FILTERS = "UPDATE_IMAGE_FILTERS";